import {
  ByteButton,
  ByteIcon,
  ByteButtonGroup,
  ByteCheckTag,
  ByteDivider,
  ByteTooltip,
  ByteSelect,
  ByteOption,
  ByteOptionGroup,
  ByteScrollbar,
  ByteRate,
  ByteTag,
  ByteSlider,
  ByteSwitch,
  ByteInput,
  ByteTimePicker,
  ByteUpload,
  ByteTimeSelect,
  ByteInputNumber,
} from '@byte-ui/components'
import { Plugin } from '@vue/runtime-core'
export default [
  ByteButton,
  ByteButtonGroup,
  ByteIcon,
  ByteTag,
  ByteCheckTag,
  ByteDivider,
  ByteTooltip,
  ByteSelect,
  ByteOption,
  ByteOptionGroup,
  ByteScrollbar,
  ByteSlider,
  ByteRate,
  ByteSwitch,
  ByteInput,
  ByteTimePicker,
  ByteUpload,
  ByteTimeSelect,
  ByteInputNumber,
] as Plugin[]
